use super::action::Action;

/// アクション名からAction enumに変換
pub fn parse_action(action_name: &str) -> Option<Action> {
    match action_name {
        "quit" => Some(Action::Quit),
        "cursor_down" => Some(Action::CursorDown),
        "cursor_up" => Some(Action::CursorUp),
        "enter" => Some(Action::Enter),
        "parent_dir" | "parent" => Some(Action::Parent),
        "toggle_hidden" => Some(Action::ToggleHidden),
        "toggle_pane" => Some(Action::TogglePane),
        "focus_left" => Some(Action::FocusLeft),
        "focus_right" => Some(Action::FocusRight),
        "refresh" => Some(Action::Refresh),
        "toggle_select" => Some(Action::ToggleSelect),
        "visual_mode" => Some(Action::VisualMode),
        "normal_mode" => Some(Action::NormalMode),
        "yank" | "yank_selection" => Some(Action::Yank),
        "cut" | "cut_selection" => Some(Action::Cut),
        "paste" => Some(Action::Paste),
        "delete" | "delete_selection" => Some(Action::Delete),
        "copy_to_other_pane" | "copy_other" => Some(Action::CopyToOtherPane),
        "move_to_other_pane" | "move_other" => Some(Action::MoveToOtherPane),
        "rename" => Some(Action::Rename),
        "create" => Some(Action::Create),
        "search" => Some(Action::SearchMode),
        "filter" => Some(Action::FilterMode),
        "search_next" => Some(Action::SearchNext),
        "search_prev" => Some(Action::SearchPrev),
        "new_tab" => Some(Action::NewTab),
        "close_tab" => Some(Action::CloseTab),
        "next_tab" => Some(Action::NextTab),
        "prev_tab" => Some(Action::PrevTab),
        "toggle_preview" => Some(Action::TogglePreview),
        "cycle_sort_method" => Some(Action::CycleSortMethod),
        "toggle_sort_reverse" => Some(Action::ToggleSortReverse),
        "toggle_sidebar" => Some(Action::ToggleSidebar),
        "add_bookmark" => Some(Action::AddBookmark),
        "show_bookmarks" => Some(Action::ShowBookmarks),
        "delete_bookmark" => Some(Action::DeleteBookmark),
        "jump_to_bookmark" => Some(Action::JumpToBookmark),
        "show_bookmark_select" | "bookmark_select" => Some(Action::ShowBookmarkSelect),
        "show_help" | "help" => Some(Action::ShowHelp),
        "extract_archive" | "extract" => Some(Action::ExtractArchive),
        "compress_to_zip" | "compress" => Some(Action::CompressToZip),
        "open_file" | "open" => Some(Action::OpenFile),
        "open_with_editor" | "edit" => Some(Action::OpenWithEditor),
        "open_with_pager" | "view" => Some(Action::OpenWithPager),
        "execute_file" | "execute" => Some(Action::ExecuteFile),
        "sync_dir_from_other" | "sync_from_other" => Some(Action::SyncDirFromOther),
        "sync_dir_to_other" | "sync_to_other" => Some(Action::SyncDirToOther),
        "command_mode" => Some(Action::CommandMode),
        "execute_command" => Some(Action::ExecuteCommand),
        "edit_config" | "config" => Some(Action::EditConfig),
        "edit_keymap" | "keymap" => Some(Action::EditKeymap),
        "edit_theme" | "theme" => Some(Action::EditTheme),
        "edit_opener" | "opener" => Some(Action::EditOpener),
        _ => None,
    }
}
